# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7bc68002-08e7-4f67-bbc8-e9927e48e18a";
      fsType = "ext4";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/3bb5fc66-66eb-40bd-9d9f-55fc100e9f17";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6bf6d122-b781-4d63-a04c-edb73ce034eb";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AF86-70B8";
      fsType = "vfat";
    };

 fileSystems."/mnt/storage" =
    { device = "/dev/md127p1";
      fsType = "ext4";
    };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/3f39e7a5-decc-48d5-897e-c0627d51e014"; }
    ];

}
